// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RepositoryLayer;

namespace CosmosMW.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211201144021_CreateTables")]
    partial class CreateTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("DomainLayer.Models.Appointments", b =>
                {
                    b.Property<Guid>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UUID")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("AppointmentDateTime")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("AppointmentDateTime");

                    b.Property<string>("AppointmentType")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("AppointmentType");

                    b.Property<Guid>("DeletedBy")
                        .HasColumnType("UUID")
                        .HasColumnName("DeletedBy");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("DeletedDate");

                    b.Property<string>("DeletedReason")
                        .HasColumnType("CHARACTER VARYING")
                        .HasColumnName("DeletedReason");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("VARCHAR(25)")
                        .HasColumnName("Diagnosis");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("ModifiedDate");

                    b.Property<string>("ModifiedReason")
                        .HasColumnType("CHARACTER VARYING")
                        .HasColumnName("ModifiedReason");

                    b.Property<Guid>("NurseId")
                        .HasColumnType("UUID")
                        .HasColumnName("NurseId");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("UUID")
                        .HasColumnName("PatientId");

                    b.Property<Guid>("PhysicianId")
                        .HasColumnType("UUID")
                        .HasColumnName("PhysicianId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("Status");

                    b.HasKey("AppointmentId")
                        .HasName("pk_appointmentid");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("DomainLayer.Models.EmployeeDetails", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UUID")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long>("Contact")
                        .HasColumnType("BIGINT")
                        .HasColumnName("Contact");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CreatedOn");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("DATE")
                        .HasColumnName("DateOfBirth");

                    b.Property<string>("Email")
                        .HasColumnType("CHARACTER VARYING")
                        .HasColumnName("Email");

                    b.Property<string>("FirstName")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("FirstName");

                    b.Property<bool>("IsActive")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("IsActive");

                    b.Property<string>("LastName")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("LastName");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("UUID")
                        .HasColumnName("RoleId");

                    b.Property<string>("Specialization")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("Specialization");

                    b.Property<string>("Title")
                        .HasColumnType("VARCHAR(15)")
                        .HasColumnName("Title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("UUID")
                        .HasColumnName("UserId");

                    b.HasKey("EmployeeId")
                        .HasName("pk_employeeid");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("EmployeeDetails");
                });

            modelBuilder.Entity("DomainLayer.Models.Master.RoleMaster", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UUID")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Role")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("Role");

                    b.Property<Guid?>("RoleMasterRoleId")
                        .HasColumnType("UUID");

                    b.HasKey("RoleId")
                        .HasName("pk_roleid");

                    b.HasIndex("RoleMasterRoleId");

                    b.ToTable("RoleMaster");
                });

            modelBuilder.Entity("DomainLayer.Models.Notes", b =>
                {
                    b.Property<Guid>("NotesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UUID")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("RecievedDateTime")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("RecievedDateTime");

                    b.Property<Guid>("RecieverId")
                        .HasColumnType("UUID")
                        .HasColumnName("RecieverId");

                    b.Property<string>("ResponseMessage")
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("ResponseMessage");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("UUID")
                        .HasColumnName("SenderId");

                    b.Property<string>("SenderMessage")
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("SenderMessage");

                    b.Property<DateTime>("SentDateTime")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("SentDateTime");

                    b.HasKey("NotesId")
                        .HasName("pk_notesid");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("DomainLayer.Models.PatientDemographicDetails", b =>
                {
                    b.Property<Guid>("PatientDemographicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UUID")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .HasColumnType("CHARACTER VARYING")
                        .HasColumnName("Address");

                    b.Property<int>("Age")
                        .HasColumnType("INT")
                        .HasColumnName("Age");

                    b.Property<long>("Contact")
                        .HasColumnType("BIGINT")
                        .HasColumnName("Contact");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("DATE")
                        .HasColumnName("DateOfBirth");

                    b.Property<string>("Email")
                        .HasColumnType("CHARACTER VARYING")
                        .HasColumnName("Email");

                    b.Property<string>("Ethinicity")
                        .HasColumnType("VARCHAR(25)")
                        .HasColumnName("Ethinicity");

                    b.Property<string>("FirstName")
                        .HasColumnType("VARCHAR(25)")
                        .HasColumnName("FirstName");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("Gender");

                    b.Property<bool>("IsFatal")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("IsFatal");

                    b.Property<string>("LastName")
                        .HasColumnType("VARCHAR(25)")
                        .HasColumnName("LastName");

                    b.Property<Guid>("PatientRelativeId")
                        .HasColumnType("UUID")
                        .HasColumnName("PatientRelativeId");

                    b.Property<string>("PreviousAllergies")
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("PreviousAllergies");

                    b.Property<string>("Race")
                        .HasColumnType("VARCHAR(25)")
                        .HasColumnName("Race");

                    b.HasKey("PatientDemographicId")
                        .HasName("pk_patientdemographicid");

                    b.HasIndex("PatientRelativeId");

                    b.ToTable("PatientDemographicDetails");
                });

            modelBuilder.Entity("DomainLayer.Models.PatientDetails", b =>
                {
                    b.Property<Guid>("PatientDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UUID")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long>("Contact")
                        .HasColumnType("BIGINT")
                        .HasColumnName("Contact");

                    b.Property<string>("FirstName")
                        .HasColumnType("VARCHAR(25)")
                        .HasColumnName("FirstName");

                    b.Property<bool>("IsActive")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("IsActive");

                    b.Property<string>("LastName")
                        .HasColumnType("VARCHAR(25)")
                        .HasColumnName("LastName");

                    b.Property<Guid>("PatientDemographicId")
                        .HasColumnType("UUID")
                        .HasColumnName("PatientDemographicId");

                    b.Property<string>("Title")
                        .HasColumnType("VARCHAR(25)")
                        .HasColumnName("Title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("UUID")
                        .HasColumnName("UserId");

                    b.HasKey("PatientDetailsId")
                        .HasName("pk_patientdetailsid");

                    b.HasIndex("PatientDemographicId");

                    b.HasIndex("UserId");

                    b.ToTable("PatientDetails");
                });

            modelBuilder.Entity("DomainLayer.Models.PatientRelativeDetails", b =>
                {
                    b.Property<Guid>("PatientRelativeDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UUID")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .HasColumnType("CHARACTER VARYING")
                        .HasColumnName("Address");

                    b.Property<long>("Contact")
                        .HasColumnType("BIGINT")
                        .HasColumnName("Contact");

                    b.Property<string>("Email")
                        .HasColumnType("CHARACTER VARYING")
                        .HasColumnName("Email");

                    b.Property<string>("FirstName")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("FirstName");

                    b.Property<string>("LastName")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("LastName");

                    b.Property<string>("Relation")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("Relation");

                    b.Property<string>("Title")
                        .HasColumnType("VARCHAR(15)")
                        .HasColumnName("Title");

                    b.HasKey("PatientRelativeDetailsId");

                    b.ToTable("PatientRelativeDetails");
                });

            modelBuilder.Entity("DomainLayer.Models.UserDetails", b =>
                {
                    b.Property<Guid>("UserDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UUID")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("IsFirstLogIn")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("IsFirstLogIn");

                    b.Property<int>("NoOfAttempts")
                        .HasColumnType("INT")
                        .HasColumnName("NoOfAttempts");

                    b.Property<string>("Password")
                        .HasColumnType("CHARACTER VARYING")
                        .HasColumnName("Password");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("UUID")
                        .HasColumnName("RoleId");

                    b.Property<bool>("Status")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("Status");

                    b.Property<string>("UserName")
                        .HasColumnType("CHARACTER VARYING")
                        .HasColumnName("UserName");

                    b.HasKey("UserDetailsId")
                        .HasName("pk_userid");

                    b.HasIndex("RoleId");

                    b.ToTable("UserDetails");
                });

            modelBuilder.Entity("DomainLayer.Models.EmployeeDetails", b =>
                {
                    b.HasOne("DomainLayer.Models.Master.RoleMaster", "RoleMaster")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomainLayer.Models.UserDetails", "UserDetails")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoleMaster");

                    b.Navigation("UserDetails");
                });

            modelBuilder.Entity("DomainLayer.Models.Master.RoleMaster", b =>
                {
                    b.HasOne("DomainLayer.Models.Master.RoleMaster", null)
                        .WithMany("lstRoleMaster")
                        .HasForeignKey("RoleMasterRoleId");
                });

            modelBuilder.Entity("DomainLayer.Models.PatientDemographicDetails", b =>
                {
                    b.HasOne("DomainLayer.Models.PatientRelativeDetails", "PatientRelativeDetails")
                        .WithMany()
                        .HasForeignKey("PatientRelativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PatientRelativeDetails");
                });

            modelBuilder.Entity("DomainLayer.Models.PatientDetails", b =>
                {
                    b.HasOne("DomainLayer.Models.PatientDemographicDetails", "PatientDemographicDetails")
                        .WithMany()
                        .HasForeignKey("PatientDemographicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomainLayer.Models.UserDetails", "UserDetails")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PatientDemographicDetails");

                    b.Navigation("UserDetails");
                });

            modelBuilder.Entity("DomainLayer.Models.UserDetails", b =>
                {
                    b.HasOne("DomainLayer.Models.Master.RoleMaster", "RoleMaster")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoleMaster");
                });

            modelBuilder.Entity("DomainLayer.Models.Master.RoleMaster", b =>
                {
                    b.Navigation("lstRoleMaster");
                });
#pragma warning restore 612, 618
        }
    }
}
