// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RepositoryLayer;

namespace CosmosMW.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211130061735_CreateUserDetailsAndRoleTable")]
    partial class CreateUserDetailsAndRoleTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("DomainLayer.Models.Master.RoleMaster", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UUID")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Role")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("Role");

                    b.Property<Guid?>("RoleMasterRoleId")
                        .HasColumnType("UUID");

                    b.HasKey("RoleId")
                        .HasName("pk_roleid");

                    b.HasIndex("RoleMasterRoleId");

                    b.ToTable("RoleMaster");
                });

            modelBuilder.Entity("DomainLayer.Models.UserDetails", b =>
                {
                    b.Property<Guid>("UserDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UUID")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("IsFirstLogIn")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("IsFirstLogIn");

                    b.Property<int>("NoOfAttempts")
                        .HasColumnType("INT")
                        .HasColumnName("NoOfAttempts");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT")
                        .HasColumnName("Password");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("UUID")
                        .HasColumnName("RoleId");

                    b.Property<bool>("Status")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("Status");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT")
                        .HasColumnName("UserName");

                    b.HasKey("UserDetailsId")
                        .HasName("pk_userid");

                    b.HasIndex("RoleId");

                    b.ToTable("UserDetails");
                });

            modelBuilder.Entity("DomainLayer.Models.Master.RoleMaster", b =>
                {
                    b.HasOne("DomainLayer.Models.Master.RoleMaster", null)
                        .WithMany("lstRoleMaster")
                        .HasForeignKey("RoleMasterRoleId");
                });

            modelBuilder.Entity("DomainLayer.Models.UserDetails", b =>
                {
                    b.HasOne("DomainLayer.Models.Master.RoleMaster", "RoleMaster")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoleMaster");
                });

            modelBuilder.Entity("DomainLayer.Models.Master.RoleMaster", b =>
                {
                    b.Navigation("lstRoleMaster");
                });
#pragma warning restore 612, 618
        }
    }
}
