// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RepositoryLayer;

namespace CosmosMW.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211201061140_CreateAndEditTables")]
    partial class CreateAndEditTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("DomainLayer.Models.EmployeeDetails", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UUID")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long>("Contact")
                        .HasColumnType("BIGINT")
                        .HasColumnName("Contact");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CreatedOn");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("DATE")
                        .HasColumnName("DateOfBirth");

                    b.Property<string>("Email")
                        .HasColumnType("CHARACTER VARYING")
                        .HasColumnName("Email");

                    b.Property<string>("FirstName")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("FirstName");

                    b.Property<bool>("IsActive")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("IsActive");

                    b.Property<string>("LastName")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("LastName");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("UUID")
                        .HasColumnName("RoleId");

                    b.Property<string>("Specialization")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("Specialization");

                    b.Property<string>("Title")
                        .HasColumnType("VARCHAR(15)")
                        .HasColumnName("Title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("UUID")
                        .HasColumnName("UserId");

                    b.HasKey("EmployeeId")
                        .HasName("pk_employeeid");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("EmployeeDetails");
                });

            modelBuilder.Entity("DomainLayer.Models.Master.RoleMaster", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UUID")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Role")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("Role");

                    b.Property<Guid?>("RoleMasterRoleId")
                        .HasColumnType("UUID");

                    b.HasKey("RoleId")
                        .HasName("pk_roleid");

                    b.HasIndex("RoleMasterRoleId");

                    b.ToTable("RoleMaster");
                });

            modelBuilder.Entity("DomainLayer.Models.Notes", b =>
                {
                    b.Property<Guid>("NotesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UUID")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("RecievedDateTime")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("RecievedDateTime");

                    b.Property<Guid>("RecieverId")
                        .HasColumnType("UUID")
                        .HasColumnName("RecieverId");

                    b.Property<string>("ResponseMessage")
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("ResponseMessage");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("UUID")
                        .HasColumnName("SenderId");

                    b.Property<string>("SenderMessage")
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("SenderMessage");

                    b.Property<DateTime>("SentDateTime")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("SentDateTime");

                    b.HasKey("NotesId")
                        .HasName("pk_notesid");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("DomainLayer.Models.UserDetails", b =>
                {
                    b.Property<Guid>("UserDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UUID")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("IsFirstLogIn")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("IsFirstLogIn");

                    b.Property<int>("NoOfAttempts")
                        .HasColumnType("INT")
                        .HasColumnName("NoOfAttempts");

                    b.Property<string>("Password")
                        .HasColumnType("CHARACTER VARYING")
                        .HasColumnName("Password");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("UUID")
                        .HasColumnName("RoleId");

                    b.Property<bool>("Status")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("Status");

                    b.Property<string>("UserName")
                        .HasColumnType("CHARACTER VARYING")
                        .HasColumnName("UserName");

                    b.HasKey("UserDetailsId")
                        .HasName("pk_userid");

                    b.HasIndex("RoleId");

                    b.ToTable("UserDetails");
                });

            modelBuilder.Entity("DomainLayer.Models.EmployeeDetails", b =>
                {
                    b.HasOne("DomainLayer.Models.Master.RoleMaster", "RoleMaster")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomainLayer.Models.UserDetails", "UserDetails")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoleMaster");

                    b.Navigation("UserDetails");
                });

            modelBuilder.Entity("DomainLayer.Models.Master.RoleMaster", b =>
                {
                    b.HasOne("DomainLayer.Models.Master.RoleMaster", null)
                        .WithMany("lstRoleMaster")
                        .HasForeignKey("RoleMasterRoleId");
                });

            modelBuilder.Entity("DomainLayer.Models.UserDetails", b =>
                {
                    b.HasOne("DomainLayer.Models.Master.RoleMaster", "RoleMaster")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoleMaster");
                });

            modelBuilder.Entity("DomainLayer.Models.Master.RoleMaster", b =>
                {
                    b.Navigation("lstRoleMaster");
                });
#pragma warning restore 612, 618
        }
    }
}
